# Configuration file for Travis CI test environment
language: php
sudo:     false
php:
  - 7.2

# Don't build feature branches etc, as they will be covered by PRs
branches:
  only:
    - /^[0-9\.]+\.x$/

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  # Disable xdebug, we're not using it and it slows composer
  - phpenv config-rm xdebug.ini
  # Ensure composer is up to date and install dependencies
  - composer self-update
  - composer install --prefer-dist
  # Generate the koharness Kohana default application
  - vendor/bin/koharness


# Run the View tests against the koharnessed application in /tmp/koharness
script: vendor/bin/phpunit

notifications:
  email: false

